import AppKit
import SwiftUI
import TurtleGitCore

@MainActor final class MergeWindowController: NSWindowController, NSWindowDelegate {
    let model: MergeWindowModel
    var onClosed: () -> Void = {}
    private var picker: LogWindowController?
    private var progressController: MergeProgressWindowController?
    init(repository: GitRepository, access: RepositoryAccessLease?) {
        model = MergeWindowModel(repository: repository, access: access)
        let window = NSWindow(contentRect: NSRect(x: 0, y: 0, width: 680, height: 570), styleMask: [.titled, .closable, .resizable], backing: .buffered, defer: false)
        window.title = "\(repository.root.lastPathComponent) – Merge – TurtleGit"
        window.minSize = NSSize(width: 660, height: 540); window.isReleasedWhenClosed = false
        window.contentViewController = NSHostingController(rootView: MergeDialog(model: model))
        super.init(window: window); window.delegate = self
        window.setContentSize(NSSize(width: 680, height: 570)); window.center()
        model.close = { [weak self] in
            guard let self, !self.model.busy, self.window?.attachedSheet == nil else { return }
            self.window?.close()
        }
        model.onProgress = { [weak self] progress in
            guard let self, let window = self.window, window.attachedSheet == nil else { progress.cancel(); return }
            let controller = MergeProgressWindowController(model: progress)
            controller.onClosed = { [weak self, weak progress] in
                guard let self, let progress else { return }
                self.progressController = nil; self.model.finish(progress)
            }
            self.progressController = controller
            if let child = controller.window { window.beginSheet(child) }
        }
        model.pickCommit = { [weak self] in
            guard let self, let window = self.window, self.picker == nil else { return }
            let picker = LogWindowController(repository: repository, access: access, onChoose: { [weak self] revision in
                if let revision { self?.model.commitRevision = revision.hash }
            })
            self.picker = picker; picker.onClosed = { [weak self] in self?.picker = nil }
            self.model.configureLogPicker(picker.model)
            if let child = picker.window { window.beginSheet(child) }
        }
    }
    func windowShouldClose(_ sender: NSWindow) -> Bool { !model.busy && sender.attachedSheet == nil }
    func windowWillClose(_ notification: Notification) { model.invalidate(); picker?.close(); picker = nil; onClosed() }
    required init?(coder: NSCoder) { fatalError("init(coder:) is not supported") }
}

@MainActor final class MergeWindowModel: ObservableObject {
    let repository: GitRepository
    private let access: RepositoryAccessLease?
    @Published var references: [CheckoutReference] = []
    @Published var currentBranch = ""
    @Published var target = CheckoutTarget.branch
    @Published var branchRevision = ""
    @Published var tagRevision = ""
    @Published var commitRevision = "HEAD"
    @Published var options = MergeOptions()
    @Published var messages = false
    @Published var messageCount = "20"
    @Published var message = "<Auto Generated by Git>"
    @Published var busy = false
    @Published var error: String?
    @Published var browseReferences = false
    var close: () -> Void = {}
    var pickCommit: () -> Void = {}
    var configureLogPicker: (LogWindowModel) -> Void = { _ in }
    var onChanged: (String) -> Void = { _ in }
    var showStashPop = false
    var onAbortRequested: (() -> Void)?
    @Published private(set) var progress: MergeProgressWindowModel?
    var onProgress: ((MergeProgressWindowModel) -> Void)?
    var onPostAction: ((MergePostAction, MergeOptions) -> Void)?
    private var invalidated = false
    var branches: [CheckoutReference] { references.filter { ($0.name.hasPrefix("refs/heads/") || $0.remote) && $0.symbolicTarget == nil && $0.name != "refs/heads/" + currentBranch } }
    var tags: [CheckoutReference] { references.filter { $0.name.hasPrefix("refs/tags/") } }
    var revision: String { switch target { case .branch: return branchRevision; case .tag: return tagRevision; case .commit: return commitRevision } }
    init(repository: GitRepository, access: RepositoryAccessLease?) { self.repository = repository; self.access = access }
    func load(revision preset: String? = nil) {
        guard !busy else { return }; busy = true
        Task {
            defer { busy = false }
            do {
                currentBranch = try await repository.branch(); references = try await repository.checkoutReferences()
                let defaults = try await repository.pushDefaults(source: "HEAD")
                let destination = defaults.destination.hasPrefix("refs/heads/") ? String(defaults.destination.dropFirst(11)) : defaults.destination
                let tracked = "refs/remotes/" + defaults.remote + "/" + destination
                branchRevision = branches.first { $0.name == tracked }?.name ?? branches.first?.name ?? ""
                tagRevision = tags.first?.name ?? ""; messageCount = String(await repository.mergeMessageCount())
                if let preset {
                    if branches.contains(where: { $0.name == preset }) { target = .branch; branchRevision = preset }
                    else if tags.contains(where: { $0.name == preset }) { target = .tag; tagRevision = preset }
                    else { target = .commit; commitRevision = preset }
                }
            } catch { self.error = error.localizedDescription }
        }
    }
    func merge() {
        guard !invalidated, !busy, !revision.isEmpty else { return }
        var snapshot = options; snapshot.revision = revision
        if messages {
            guard let count = Int(messageCount), count >= 0 else { error = MergeFailure.logCount.localizedDescription; return }
            snapshot.logCount = count
        }
        snapshot.message = message == "<Auto Generated by Git>" ? "" : message
        busy = true
        let progress = MergeProgressWindowModel(repository: repository, access: access, options: snapshot, target: target, showStashPop: showStashPop)
        self.progress = progress
        progress.onChanged = onChanged; progress.onPostAction = onPostAction; progress.onAbortRequested = onAbortRequested
        progress.close = { [weak self, weak progress] in if let progress { self?.finish(progress) } }
        onProgress?(progress); progress.start()
    }
    func invalidate() { invalidated = true }
    func finish(_ progress: MergeProgressWindowModel) {
        guard self.progress === progress, !progress.busy, !progress.confirmingCancellation, !progress.confirmingDeletion else { return }
        self.progress = nil; busy = false; close()
    }
}

private struct MergeDialog: View {
    @ObservedObject var model: MergeWindowModel
    var body: some View {
        VStack(alignment: .leading, spacing: 12) {
            HStack { Text("Current branch:").frame(width: 115, alignment: .leading); Text(model.currentBranch.isEmpty ? "Detached HEAD" : model.currentBranch).foregroundStyle(.blue) }
            GroupBox("From") {
                VStack(spacing: 8) {
                    HStack {
                        SwitchRadio(title: "Branch", target: .branch, selection: $model.target).frame(width: 95)
                        ReferencePopup(references: model.branches, selection: $model.branchRevision).disabled(model.target != .branch)
                        Button("…") { model.browseReferences = true }.accessibilityLabel("Browse references").disabled(model.target != .branch)
                    }
                    HStack {
                        SwitchRadio(title: "Tag", target: .tag, selection: $model.target).frame(width: 95)
                        ReferencePopup(references: model.tags, selection: $model.tagRevision).disabled(model.target != .tag)
                        Color.clear.frame(width: 29)
                    }
                    HStack {
                        SwitchRadio(title: "Commit", target: .commit, selection: $model.target).frame(width: 95)
                        TextField("Commit", text: $model.commitRevision).disabled(model.target != .commit)
                        Button("…") { model.pickCommit() }.accessibilityLabel("Choose commit").disabled(model.target != .commit)
                    }
                }.padding(8)
            }
            GroupBox("Option") {
                VStack(alignment: .leading, spacing: 10) {
                    HStack {
                        Toggle("Squash", isOn: $model.options.squash).frame(width: 260, alignment: .leading).disabled(model.options.noFastForward)
                        Toggle("Messages", isOn: $model.messages)
                        TextField("Count", text: $model.messageCount).frame(width: 55).disabled(!model.messages).accessibilityLabel("Number of commit messages")
                    }
                    HStack {
                        Toggle("No Fast Forward", isOn: $model.options.noFastForward).frame(width: 260, alignment: .leading).disabled(model.options.squash || model.options.fastForwardOnly)
                        Toggle("Fast Forward Only", isOn: $model.options.fastForwardOnly).disabled(model.options.noFastForward)
                    }
                    Toggle("No Commit", isOn: $model.options.noCommit)
                    HStack {
                        Text("Strategy")
                        Picker("Merge strategy", selection: $model.options.strategy) { Text("").tag(""); ForEach(MergeOptions.strategies, id: \.self) { Text($0).tag($0) } }.labelsHidden().frame(width: 125)
                        Picker("Strategy option", selection: $model.options.strategyOption) { Text("").tag(""); ForEach(MergeOptions.strategyOptions, id: \.self) { Text($0).tag($0) } }.labelsHidden().disabled(model.options.strategy != "recursive")
                        TextField("Parameter", text: $model.options.strategyParameter).frame(width: 75).disabled(model.options.strategy != "recursive" || !["rename-threshold", "subtree"].contains(model.options.strategyOption))
                    }
                }.toggleStyle(.checkbox).frame(maxWidth: .infinity, alignment: .leading).padding(8)
            }
            GroupBox("Merge Message") {
                TextEditor(text: $model.message).font(.system(.body, design: .monospaced)).frame(minHeight: 110).disabled(model.options.squash).padding(5)
            }
            HStack {
                if model.busy { ProgressView().controlSize(.small) }
                Spacer()
                Button("OK") { model.merge() }.keyboardShortcut(.defaultAction).disabled(model.busy || model.revision.isEmpty)
                Button("Cancel") { model.close() }.keyboardShortcut(.cancelAction).disabled(model.busy)
                Button("Help") { NSWorkspace.shared.open(URL(string: "https://tortoisegit.org/docs/tortoisegit/tgit-dug-merge.html")!) }
            }
        }.padding(16).disabled(model.busy)
        .alert("Merge failed", isPresented: Binding(get: { model.error != nil }, set: { if !$0 { model.error = nil } })) { Button("OK") { model.error = nil } } message: { Text(model.error ?? "") }
        .sheet(isPresented: $model.browseReferences) { MergeReferenceChooser(model: model) }
    }
}

private struct MergeReferenceChooser: View {
    @ObservedObject var model: MergeWindowModel
    @State private var filter = ""
    @State private var selection: String?
    var body: some View {
        VStack(alignment: .leading, spacing: 12) {
            Text("Browse references").font(.headline)
            TextField("Filter", text: $filter)
            List(selection: $selection) { ForEach(model.branches.filter { filter.isEmpty || $0.label.localizedCaseInsensitiveContains(filter) }, id: \.name) { Text($0.label).tag($0.name) } }
            HStack { Spacer(); Button("Cancel") { model.browseReferences = false }.keyboardShortcut(.cancelAction)
                Button("OK") { if let selection { model.branchRevision = selection }; model.browseReferences = false }.disabled(selection == nil).keyboardShortcut(.defaultAction)
            }
        }.padding(16).frame(width: 580, height: 400)
    }
}

enum MergePostAction: String, CaseIterable, Hashable {
    case resolve, commit, mergeUnrelated, stash, stashPop, removeBranch, push
    var title: String {
        switch self {
        case .resolve: return "Resolve…"
        case .commit: return "Commit…"
        case .mergeUnrelated: return "Merge unrelated histories"
        case .stash: return "Stash Save…"
        case .stashPop: return "Stash Pop"
        case .removeBranch: return "Remove branch"
        case .push: return "Push…"
        }
    }
    var icon: MenuIcon {
        switch self { case .resolve: return .resolve; case .commit: return .commit; case .mergeUnrelated: return .merge; case .stash: return .stash; case .stashPop: return .stashPop; case .removeBranch: return .remove; case .push: return .push }
    }
}
@MainActor final class MergeProgressWindowModel: ObservableObject {
    let repository: GitRepository
    let options: MergeOptions
    let target: CheckoutTarget
    let showStashPop: Bool
    private let access: RepositoryAccessLease?
    private var cancellation = OperationCancellation()
    private var started = false
    private let preferences: UserDefaults
    private let autoClosePolicy: GitProgressAutoClose
    static let conflictHintPreference = "MergeConflictsNeedsCommit"
    static let conflictHint = """
    While merging, i.e. integrating changes of another (remote) branch into your local branch, a conflict in at least one file occurred. This means that you need to resolve this manually (i.e., you need to integrate your changes into a file which was also modified on another branch).

    After resolving all files, you need to perform a commit in order to complete the merge.

    If you want to abort the merge, do a hard reset on HEAD or select abort merge on the context menu.

    See help for more information.
    """
    @Published private(set) var confirmingConflictHint = false
    var presentConflictHint: (() async -> Bool)?
    @Published private(set) var checkingDismissal = false
    var onAbortRequested: (() -> Void)?
    @Published private(set) var busy = true
    @Published private(set) var success = false
    @Published private(set) var cancelled = false
    @Published private(set) var output = ""
    @Published private(set) var percentage: Int?
    @Published private(set) var currentWork = ""
    @Published private(set) var cancelling = false
    @Published private(set) var confirmingCancellation = false
    private(set) var rawOutput = ""
    private var outputState: GitProgressOutputState
    var outputLimit: Int { outputState.limit }
    var canCancel: Bool { busy && !cancelling && !confirmingCancellation && !confirmingConflictHint }
    var confirmCancellation: (@escaping (Bool) -> Void) -> Void = { $0(false) }
    @Published private(set) var postActions: [MergePostAction] = []
    @Published private(set) var confirmingDeletion = false
    @Published var deletionError: String?
    var close: () -> Void = {}
    var onChanged: (String) -> Void = { _ in }
    var onPostAction: ((MergePostAction, MergeOptions) -> Void)?
    var confirmDeletion: (String, @escaping (Bool) -> Void) -> Void = { _, choose in choose(false) }
    init(repository: GitRepository, access: RepositoryAccessLease?, options: MergeOptions, target: CheckoutTarget, showStashPop: Bool, preferences: UserDefaults = .standard) { self.repository = repository; self.access = access; self.options = options; self.target = target; self.showStashPop = showStashPop; self.preferences = preferences; self.autoClosePolicy = GitProgressAutoClose(preferences: preferences); outputState = GitProgressOutputState(preferences: preferences) }
    func start() { Task { await run() } }
    func run() async { guard !started else { return }; started = true; await execute(options) }
    func cancel() {
        guard canCancel else { return }; let token = cancellation
        if preferences.bool(forKey: "ConfirmKillProcess") {
            confirmingCancellation = true; var answered = false
            confirmCancellation { [weak self] accepted in
                guard !answered, let self, self.confirmingCancellation, self.cancellation === token else { return }
                answered = true; self.confirmingCancellation = false
                if self.busy && accepted { self.cancelling = true; token.cancel() }
                self.finishResult()
            }
        } else { cancelling = true; token.cancel() }
    }
    private func finishResult() {
        guard !busy, !confirmingCancellation, !confirmingConflictHint else { return }
        if autoClosePolicy.shouldClose(success: success, postActionCount: postActions.count) { close() }
        else if cancelled, onAbortRequested != nil { cancelResult() }
    }
    private func consume(_ emission: GitCliOutputParser.Emission, parser: GitCliOutputParser) {
        outputState.consume(emission, parser: parser)
        output = outputState.output; percentage = outputState.percentage; currentWork = outputState.currentWork
    }
    private func streamMerge(_ snapshot: MergeOptions) async throws -> String {
        let parser = GitCliOutputParser(limit: outputState.limit)
        let (updates, continuation) = AsyncStream<Void>.makeStream(bufferingPolicy: .bufferingNewest(1))
        let operation = Task {
            defer { continuation.finish() }
            return try await repository.merge(snapshot, cancellation: cancellation, onOutput: { chunk in parser.appendChunk(chunk.data); continuation.yield(()) })
        }
        for await _ in updates { consume(parser.processPending(), parser: parser) }
        consume(parser.processPending(), parser: parser); consume(parser.finish(), parser: parser)
        return try await operation.value
    }
    private func validateAccess() throws {
        if GitRuntime.isAppStoreBuild && (access?.hasSecurityScope != true || access?.contains(repository.root) != true) { throw RepositoryAccessFailure.securityScopeUnavailable }
    }
    private func execute(_ snapshot: MergeOptions) async {
        busy = true; success = false; cancelled = false; cancelling = false; outputState.reset(); output = ""; rawOutput = ""; percentage = nil; currentWork = ""; postActions = []
        do { try validateAccess() }
        catch { output = error.localizedDescription; rawOutput = output; busy = false; onChanged(rawOutput); return }
        do { rawOutput = try await streamMerge(snapshot); if !outputState.hasOutput { output = rawOutput }; success = true }
        catch {
            if let failure = error as? GitCommandCancellationFailure { rawOutput = failure.result.text + "\n" + failure.localizedDescription }
            else { rawOutput = error.localizedDescription }
            let message: String
            if let failure = error as? GitFailure, failure.arguments.first == "merge", outputState.hasOutput { message = "Git command failed (\(failure.code))." }
            else { message = error.localizedDescription }
            output += (output.isEmpty || output.hasSuffix("\n") ? "" : "\n") + message; cancelled = cancellation.isCancelled
        }
        if success {
            if showStashPop { postActions.append(.stashPop) }
            if options.noCommit || options.squash { postActions.append(.commit) }
            else if target == .branch {
                if options.revision.hasPrefix("refs/heads/") { postActions.append(.removeBranch) }
                postActions.append(.push)
            }
        } else {
            if (try? await repository.status(refreshIndex: false).contains { $0.state == .conflicted }) == true {
                if !preferences.bool(forKey: Self.conflictHintPreference), let presentConflictHint {
                    confirmingConflictHint = true
                    let suppress = await presentConflictHint()
                    confirmingConflictHint = false
                    if suppress { preferences.set(true, forKey: Self.conflictHintPreference) }
                }
                postActions += [.resolve, .commit]
            }
            let head = try? await repository.run(["rev-parse", "--verify", "--end-of-options", "HEAD^{commit}"]).text.trimmingCharacters(in: .newlines)
            let revision = try? await repository.run(["rev-parse", "--verify", "--end-of-options", options.revision + "^{commit}"]).text.trimmingCharacters(in: .newlines)
            var common = false
            if let head, let revision { common = (try? await repository.run(["merge-base", head, revision], successfulExitCodes: 0...1).stdout.isEmpty) == false }
            if !common { postActions.append(.mergeUnrelated) }
            postActions.append(.stash)
        }
        busy = false; cancelling = false; onChanged(rawOutput); finishResult()
    }
    func cancelResult() {
        guard !busy, !confirmingCancellation, !confirmingConflictHint, !confirmingDeletion, !checkingDismissal else { return }
        checkingDismissal = true
        Task {
            var conflicts = false
            do { try validateAccess(); conflicts = try await repository.status(refreshIndex: false).contains { $0.state == .conflicted } } catch {}
            checkingDismissal = false
            close()
            if conflicts { onAbortRequested?() }
        }
    }
    func perform(_ action: MergePostAction) {
        guard !busy, !confirmingCancellation, !confirmingDeletion, !checkingDismissal, postActions.contains(action) else { return }
        if action == .mergeUnrelated {
            var snapshot = options; snapshot.allowUnrelatedHistories = true
            busy = true; cancellation = OperationCancellation()
            Task { await execute(snapshot) }
        } else if action == .removeBranch {
            confirmingDeletion = true
            confirmDeletion(String(options.revision.dropFirst("refs/heads/".count))) { [weak self] accepted in
                guard let self, self.confirmingDeletion else { return }
                self.confirmingDeletion = false
                if accepted { self.deleteBranch() }
            }
        } else if let onPostAction { close(); onPostAction(action, options) }
    }
    private func deleteBranch() {
        guard !busy, options.revision.hasPrefix("refs/heads/") else { return }; busy = true; cancellation = OperationCancellation()
        Task {
            do {
                try validateAccess()
                let result = try await repository.run(["branch", "-D", "--", String(options.revision.dropFirst("refs/heads/".count))], cancellation: cancellation)
                rawOutput += "\n" + result.text; output += "\n" + result.text; postActions.removeAll { $0 == .removeBranch }
            } catch { deletionError = error.localizedDescription; rawOutput += "\n" + error.localizedDescription; output += "\n" + error.localizedDescription }
            busy = false; cancelling = false; onChanged(rawOutput)
        }
    }
}
@MainActor final class MergeProgressWindowController: NSWindowController, NSWindowDelegate {
    let model: MergeProgressWindowModel
    var onClosed: () -> Void = {}
    init(model: MergeProgressWindowModel) {
        self.model = model
        let window = NSWindow(contentRect: NSRect(x: 0, y: 0, width: 780, height: 420), styleMask: [.titled, .closable, .resizable], backing: .buffered, defer: false)
        window.title = "\(model.repository.root.lastPathComponent) – Merge Progress – TurtleGit"
        window.contentMinSize = NSSize(width: 560, height: 300); window.isReleasedWhenClosed = false
        window.contentViewController = NSHostingController(rootView: MergeProgressDialog(model: model))
        super.init(window: window); window.delegate = self
        model.close = { [weak self] in
            guard let self, !self.model.busy, !self.model.confirmingDeletion, !self.model.confirmingCancellation, !self.model.checkingDismissal, self.window?.attachedSheet == nil else { return }
            if let window = self.window { window.sheetParent?.endSheet(window); window.close() }
        }
        model.presentConflictHint = { [weak window] in
            guard let window, window.attachedSheet == nil else { return false }
            return await withCheckedContinuation { continuation in
                let alert = NSAlert(); alert.alertStyle = .informational
                alert.messageText = "TurtleGit"; alert.informativeText = MergeProgressWindowModel.conflictHint
                alert.addButton(withTitle: "OK")
                alert.showsSuppressionButton = true; alert.suppressionButton?.title = "Don't show this message again"
                alert.beginSheetModal(for: window) { _ in continuation.resume(returning: alert.suppressionButton?.state == .on) }
            }
        }
        model.confirmCancellation = { [weak window] choose in
            guard let window, window.attachedSheet == nil else { choose(false); return }
            let alert = NSAlert(); alert.alertStyle = .informational; alert.messageText = "The process is still running."; alert.informativeText = "Are you sure to abort?"
            let yes = alert.addButton(withTitle: "Yes"); alert.addButton(withTitle: "No"); yes.keyEquivalent = "\r"; alert.window.defaultButtonCell = yes.cell as? NSButtonCell
            alert.beginSheetModal(for: window) { choose($0 == .alertFirstButtonReturn) }
        }
        model.confirmDeletion = { [weak window] branch, choose in
            guard let window, window.attachedSheet == nil else { choose(false); return }
            let alert = NSAlert(); alert.alertStyle = .warning; alert.messageText = "Delete branch \"\(branch)\"?"
            alert.addButton(withTitle: "Delete"); alert.addButton(withTitle: "Abort")
            alert.beginSheetModal(for: window) { choose($0 == .alertFirstButtonReturn) }
        }
    }
    func windowShouldClose(_ sender: NSWindow) -> Bool {
        if model.confirmingConflictHint || model.confirmingCancellation { return false }
        if model.busy { model.cancel(); return false }
        guard !model.confirmingDeletion, !model.checkingDismissal, sender.attachedSheet == nil else { return false }
        model.cancelResult(); return false
    }
    func windowWillClose(_ notification: Notification) { onClosed() }
    required init?(coder: NSCoder) { fatalError("init(coder:) is not supported") }
}
struct MergeProgressDialog: View {
    @ObservedObject var model: MergeProgressWindowModel
    var body: some View {
        VStack(alignment: .leading, spacing: 12) {
            Text("Merge \(model.options.revision)").font(.headline)
            ScrollViewReader { reader in
                ScrollView { VStack(alignment: .leading, spacing: 0) { Text(model.output).font(.system(.body, design: .monospaced)).textSelection(.enabled).frame(maxWidth: .infinity, alignment: .leading); Color.clear.frame(height: 1).id("merge-output-end") } }
                    .onChange(of: model.output) { _ in reader.scrollTo("merge-output-end", anchor: .bottom) }
            }.frame(maxWidth: .infinity, maxHeight: .infinity).padding(8).background(Color(nsColor: .textBackgroundColor))
            if model.busy, let percentage = model.percentage { ProgressView(value: Double(percentage), total: 100).tint(.green) }
            if !model.currentWork.isEmpty { Text(model.currentWork).font(.caption).lineLimit(2) }
            HStack {
                if model.busy { if model.percentage == nil { ProgressView().controlSize(.small) }; Text(model.cancelling ? "Cancelling…" : "Running…") }
                else { Text(model.cancelled ? "Cancelled" : model.success ? "Finished" : "Merge failed").foregroundStyle(model.success ? Color.green : Color.red) }
                Spacer()
            }
            HStack {
                if let first = model.postActions.first {
                    HStack(spacing: 2) {
                        Button { model.perform(first) } label: { CommandLabel(title: first.title, icon: first.icon) }
                        Menu { ForEach(model.postActions, id: \.self) { action in Button { model.perform(action) } label: { CommandLabel(title: action.title, icon: action.icon) } } } label: { Image(systemName: "chevron.down").accessibilityLabel("Merge post-actions") }.menuStyle(.borderlessButton).fixedSize()
                    }.disabled(model.busy || model.confirmingCancellation || model.confirmingDeletion || model.checkingDismissal)
                }
                Spacer()
                if model.busy { Button(model.cancelling ? "Cancelling…" : "Cancel") { model.cancel() }.keyboardShortcut(.cancelAction).disabled(!model.canCancel) }
                else {
                    if !model.success { Button("Cancel") { model.cancelResult() }.keyboardShortcut(.cancelAction).disabled(model.confirmingCancellation || model.confirmingDeletion || model.checkingDismissal) }
                    Button("Close") { model.close() }.keyboardShortcut(.defaultAction).disabled(model.confirmingCancellation || model.confirmingDeletion || model.checkingDismissal)
                }
            }
        }.padding(12)
        .alert("Delete branch failed", isPresented: Binding(get: { model.deletionError != nil }, set: { if !$0 { model.deletionError = nil } })) { Button("OK") { model.deletionError = nil } } message: { Text(model.deletionError ?? "") }
    }
}

enum MergeAbortPostAction: String, CaseIterable, Hashable {
    case retry, submoduleUpdate, good, bad, skip, reset, clean
    var title: String {
        switch self { case .retry: return "Retry"; case .submoduleUpdate: return "Submodule Update…"; case .good: return "Bisect good"; case .bad: return "Bisect bad"; case .skip: return "Bisect skip"; case .reset: return "Bisect reset"; case .clean: return "Clean up…" }
    }
    var icon: MenuIcon {
        switch self { case .retry: return .refresh; case .submoduleUpdate: return .fetch; case .good: return .bisectGood; case .bad: return .bisectBad; case .skip: return .bisect; case .reset: return .bisectReset; case .clean: return .clean }
    }
    var bisectOperation: BisectOperation? { BisectOperation(rawValue: rawValue) }
}
@MainActor final class MergeAbortWindowModel: ObservableObject {
    let repository: GitRepository
    private let access: RepositoryAccessLease?
    private var invalidated = false
    private var cancellation = OperationCancellation()
    private var operationMode = MergeAbortMode.merge
    @Published var mode = MergeAbortMode.merge
    @Published private(set) var busy = false
    @Published private(set) var showingProgress = false
    @Published private(set) var success = false
    @Published private(set) var cancelled = false
    @Published private(set) var output = ""
    @Published private(set) var postActions: [MergeAbortPostAction] = []
    var onChanged: (String) -> Void = { _ in }
    var onShowModified: (() -> Void)?
    var onPostAction: ((MergeAbortPostAction) -> Void)?
    var onResize: (Bool) -> Void = { _ in }
    private let preferences: UserDefaults
    private var autoClosePolicy = GitProgressAutoClose.manual
    var close: () -> Void = {}
    init(repository: GitRepository, access: RepositoryAccessLease?, preferences: UserDefaults = .standard) { self.repository = repository; self.access = access; self.preferences = preferences }
    func invalidate() { invalidated = true }
    func showModified() { guard !invalidated, !busy, !showingProgress else { return }; onShowModified?() }
    func abort() {
        guard !invalidated, !busy, !showingProgress else { return }
        operationMode = mode; showingProgress = true; onResize(true); start()
    }
    private func start() {
        autoClosePolicy = GitProgressAutoClose(preferences: preferences)
        busy = true; success = false; cancelled = false; output = ""; postActions = []; cancellation = OperationCancellation()
        Task {
            do {
                if GitRuntime.isAppStoreBuild && (access?.hasSecurityScope != true || access?.contains(repository.root) != true) { throw RepositoryAccessFailure.securityScopeUnavailable }
                output = try await repository.abortMerge(mode: operationMode, cancellation: cancellation)
                success = true
                if operationMode != .merge {
                    if operationMode == .hard, (try? await repository.submoduleUpdatePaths().isEmpty) == false { postActions.append(.submoduleUpdate) }
                    if let path = try? await repository.run(["rev-parse", "--git-path", "BISECT_START"]).text.trimmingCharacters(in: .newlines) {
                        let url = path.hasPrefix("/") ? URL(fileURLWithPath: path) : repository.root.appendingPathComponent(path)
                        if FileManager.default.fileExists(atPath: url.path) { postActions += [.good, .bad, .skip, .reset] }
                    }
                    if operationMode == .hard { postActions.append(.clean) }
                }
            } catch { output = error.localizedDescription; cancelled = cancellation.isCancelled; postActions = [.retry] }
            busy = false; onChanged(output)
            if autoClosePolicy.shouldClose(success: success, postActionCount: postActions.count) { close() }
        }
    }
    func cancel() { guard busy else { return }; cancellation.cancel() }
    func perform(_ action: MergeAbortPostAction) {
        guard !invalidated, !busy, postActions.contains(action) else { return }
        if action == .retry {
            if operationMode == .merge { mode = .merge; showingProgress = false; onResize(false) }
            else { start() }
        } else if let onPostAction { close(); onPostAction(action) }
    }
}
@MainActor final class MergeAbortWindowController: NSWindowController, NSWindowDelegate {
    let model: MergeAbortWindowModel
    var onClosed: () -> Void = {}
    init(repository: GitRepository, access: RepositoryAccessLease?) {
        model = MergeAbortWindowModel(repository: repository, access: access)
        let window = NSWindow(contentRect: NSRect(x: 0, y: 0, width: 660, height: 265), styleMask: [.titled, .closable], backing: .buffered, defer: false)
        window.title = "\(repository.root.lastPathComponent) – Abort Merge – TurtleGit"; window.isReleasedWhenClosed = false
        window.contentViewController = NSHostingController(rootView: MergeAbortDialog(model: model))
        super.init(window: window); window.delegate = self; window.center()
        model.close = { [weak self] in guard let self, !self.model.busy, self.window?.attachedSheet == nil else { return }; self.window?.close() }
        model.onResize = { [weak window] progress in window?.setContentSize(progress ? NSSize(width: 760, height: 420) : NSSize(width: 660, height: 265)) }
    }
    func windowShouldClose(_ sender: NSWindow) -> Bool { if model.busy { model.cancel(); return false }; return sender.attachedSheet == nil }
    func windowWillClose(_ notification: Notification) { model.invalidate(); onClosed() }
    required init?(coder: NSCoder) { fatalError("init(coder:) is not supported") }
}
private struct MergeAbortDialog: View {
    @ObservedObject var model: MergeAbortWindowModel
    var body: some View {
        VStack(alignment: .leading, spacing: 12) {
            if model.showingProgress {
                ScrollView { Text(model.output).font(.system(.body, design: .monospaced)).textSelection(.enabled).frame(maxWidth: .infinity, alignment: .leading) }.frame(maxWidth: .infinity, maxHeight: .infinity).padding(8).background(Color(nsColor: .textBackgroundColor))
                HStack { if model.busy { ProgressView().controlSize(.small) }; Text(model.busy ? "Resetting HEAD…" : model.cancelled ? "Cancelled" : model.success ? "Finished" : "Reset failed").foregroundStyle(model.busy ? Color.primary : model.success ? Color.green : Color.red); Spacer() }
                HStack {
                    if let first = model.postActions.first {
                        Button { model.perform(first) } label: { CommandLabel(title: first.title, icon: first.icon) }
                        Menu { ForEach(model.postActions, id: \.self) { action in Button { model.perform(action) } label: { CommandLabel(title: action.title, icon: action.icon) } } } label: { Image(systemName: "chevron.down").accessibilityLabel("Reset post-actions") }.menuStyle(.borderlessButton).fixedSize()
                    }
                    Spacer()
                    if model.busy { Button("Cancel") { model.cancel() }.keyboardShortcut(.cancelAction) }
                    else { Button("Close") { model.close() }.keyboardShortcut(.defaultAction) }
                }
            } else {
                Text("In order to abort a merge progress a reset (to HEAD) is needed.")
                GroupBox("Reset Type") {
                    Picker("Reset Type", selection: $model.mode) {
                        Text("Merge: Resets the index and try to reconstruct the pre-merge state").tag(MergeAbortMode.merge)
                        Text("Mixed: Leave working tree untouched, reset index").tag(MergeAbortMode.mixed)
                        Text("Hard: Reset working tree and index (discard all local changes)").tag(MergeAbortMode.hard)
                    }.pickerStyle(.radioGroup).labelsHidden().padding(8).frame(maxWidth: .infinity, alignment: .leading)
                }
                Button { model.showModified() } label: { CommandLabel(title: "Show modified files in working tree", icon: .compare) }.frame(maxWidth: .infinity).disabled(model.onShowModified == nil)
                HStack { Spacer(); Button("OK") { model.abort() }.keyboardShortcut(.defaultAction); Button("Cancel") { model.close() }.keyboardShortcut(.cancelAction); Button("Help") { NSWorkspace.shared.open(URL(string: "https://tortoisegit.org/docs/tortoisegit/tgit-dug-merge.html")!) } }
            }
        }.padding(16)
    }
}
