import AppKit
import SwiftUI
import TurtleGitCore

@MainActor final class MergeWindowController: NSWindowController, NSWindowDelegate {
    let model: MergeWindowModel
    var onClosed: () -> Void = {}
    private var picker: LogWindowController?
    init(repository: GitRepository, access: RepositoryAccessLease?) {
        model = MergeWindowModel(repository: repository, access: access)
        let window = NSWindow(contentRect: NSRect(x: 0, y: 0, width: 680, height: 570), styleMask: [.titled, .closable, .resizable], backing: .buffered, defer: false)
        window.title = "\(repository.root.lastPathComponent) – Merge – TurtleGit"
        window.minSize = NSSize(width: 660, height: 540); window.isReleasedWhenClosed = false
        window.contentViewController = NSHostingController(rootView: MergeDialog(model: model))
        super.init(window: window); window.delegate = self
        window.setContentSize(NSSize(width: 680, height: 570)); window.center()
        model.close = { [weak window] in window?.close() }
        model.pickCommit = { [weak self] in
            guard let self, let window = self.window, self.picker == nil else { return }
            let picker = LogWindowController(repository: repository, access: access, onChoose: { [weak self] revision in
                if let revision { self?.model.commitRevision = revision.hash }
            })
            self.picker = picker; picker.onClosed = { [weak self] in self?.picker = nil }
            self.model.configureLogPicker(picker.model)
            if let child = picker.window { window.beginSheet(child) }
        }
    }
    func windowShouldClose(_ sender: NSWindow) -> Bool { !model.busy }
    func windowWillClose(_ notification: Notification) { picker?.close(); picker = nil; onClosed() }
    required init?(coder: NSCoder) { fatalError("init(coder:) is not supported") }
}

@MainActor final class MergeWindowModel: ObservableObject {
    let repository: GitRepository
    private let access: RepositoryAccessLease?
    @Published var references: [CheckoutReference] = []
    @Published var currentBranch = ""
    @Published var target = CheckoutTarget.branch
    @Published var branchRevision = ""
    @Published var tagRevision = ""
    @Published var commitRevision = "HEAD"
    @Published var options = MergeOptions()
    @Published var messages = false
    @Published var messageCount = "20"
    @Published var message = "<Auto Generated by Git>"
    @Published var busy = false
    @Published var error: String?
    @Published var browseReferences = false
    var close: () -> Void = {}
    var pickCommit: () -> Void = {}
    var configureLogPicker: (LogWindowModel) -> Void = { _ in }
    var onChanged: (String) -> Void = { _ in }
    var branches: [CheckoutReference] { references.filter { ($0.name.hasPrefix("refs/heads/") || $0.remote) && $0.symbolicTarget == nil && $0.name != "refs/heads/" + currentBranch } }
    var tags: [CheckoutReference] { references.filter { $0.name.hasPrefix("refs/tags/") } }
    var revision: String { switch target { case .branch: return branchRevision; case .tag: return tagRevision; case .commit: return commitRevision } }
    init(repository: GitRepository, access: RepositoryAccessLease?) { self.repository = repository; self.access = access }
    func load() {
        guard !busy else { return }; busy = true
        Task {
            defer { busy = false }
            do {
                currentBranch = try await repository.branch(); references = try await repository.checkoutReferences()
                let defaults = try await repository.pushDefaults(source: "HEAD")
                let destination = defaults.destination.hasPrefix("refs/heads/") ? String(defaults.destination.dropFirst(11)) : defaults.destination
                let tracked = "refs/remotes/" + defaults.remote + "/" + destination
                branchRevision = branches.first { $0.name == tracked }?.name ?? branches.first?.name ?? ""
                tagRevision = tags.first?.name ?? ""; messageCount = String(await repository.mergeMessageCount())
            } catch { self.error = error.localizedDescription }
        }
    }
    func merge() {
        guard !busy, !revision.isEmpty else { return }
        var snapshot = options; snapshot.revision = revision
        if messages {
            guard let count = Int(messageCount), count >= 0 else { error = MergeFailure.logCount.localizedDescription; return }
            snapshot.logCount = count
        }
        snapshot.message = message == "<Auto Generated by Git>" ? "" : message
        busy = true
        Task {
            defer { busy = false }
            do { let output = try await repository.merge(snapshot); onChanged(output); close() }
            catch { let details = error.localizedDescription; self.error = details; onChanged(details) }
        }
    }
}

private struct MergeDialog: View {
    @ObservedObject var model: MergeWindowModel
    var body: some View {
        VStack(alignment: .leading, spacing: 12) {
            HStack { Text("Current branch:").frame(width: 115, alignment: .leading); Text(model.currentBranch.isEmpty ? "Detached HEAD" : model.currentBranch).foregroundStyle(.blue) }
            GroupBox("From") {
                VStack(spacing: 8) {
                    HStack {
                        SwitchRadio(title: "Branch", target: .branch, selection: $model.target).frame(width: 95)
                        ReferencePopup(references: model.branches, selection: $model.branchRevision).disabled(model.target != .branch)
                        Button("…") { model.browseReferences = true }.accessibilityLabel("Browse references").disabled(model.target != .branch)
                    }
                    HStack {
                        SwitchRadio(title: "Tag", target: .tag, selection: $model.target).frame(width: 95)
                        ReferencePopup(references: model.tags, selection: $model.tagRevision).disabled(model.target != .tag)
                        Color.clear.frame(width: 29)
                    }
                    HStack {
                        SwitchRadio(title: "Commit", target: .commit, selection: $model.target).frame(width: 95)
                        TextField("Commit", text: $model.commitRevision).disabled(model.target != .commit)
                        Button("…") { model.pickCommit() }.accessibilityLabel("Choose commit").disabled(model.target != .commit)
                    }
                }.padding(8)
            }
            GroupBox("Option") {
                VStack(alignment: .leading, spacing: 10) {
                    HStack {
                        Toggle("Squash", isOn: $model.options.squash).frame(width: 260, alignment: .leading).disabled(model.options.noFastForward)
                        Toggle("Messages", isOn: $model.messages)
                        TextField("Count", text: $model.messageCount).frame(width: 55).disabled(!model.messages).accessibilityLabel("Number of commit messages")
                    }
                    HStack {
                        Toggle("No Fast Forward", isOn: $model.options.noFastForward).frame(width: 260, alignment: .leading).disabled(model.options.squash || model.options.fastForwardOnly)
                        Toggle("Fast Forward Only", isOn: $model.options.fastForwardOnly).disabled(model.options.noFastForward)
                    }
                    Toggle("No Commit", isOn: $model.options.noCommit)
                    HStack {
                        Text("Strategy")
                        Picker("Merge strategy", selection: $model.options.strategy) { Text("").tag(""); ForEach(MergeOptions.strategies, id: \.self) { Text($0).tag($0) } }.labelsHidden().frame(width: 125)
                        Picker("Strategy option", selection: $model.options.strategyOption) { Text("").tag(""); ForEach(MergeOptions.strategyOptions, id: \.self) { Text($0).tag($0) } }.labelsHidden().disabled(model.options.strategy != "recursive")
                        TextField("Parameter", text: $model.options.strategyParameter).frame(width: 75).disabled(model.options.strategy != "recursive" || !["rename-threshold", "subtree"].contains(model.options.strategyOption))
                    }
                }.toggleStyle(.checkbox).frame(maxWidth: .infinity, alignment: .leading).padding(8)
            }
            GroupBox("Merge Message") {
                TextEditor(text: $model.message).font(.system(.body, design: .monospaced)).frame(minHeight: 110).disabled(model.options.squash).padding(5)
            }
            HStack {
                if model.busy { ProgressView().controlSize(.small) }
                Spacer()
                Button("OK") { model.merge() }.keyboardShortcut(.defaultAction).disabled(model.busy || model.revision.isEmpty)
                Button("Cancel") { model.close() }.keyboardShortcut(.cancelAction).disabled(model.busy)
                Button("Help") { NSWorkspace.shared.open(URL(string: "https://tortoisegit.org/docs/tortoisegit/tgit-dug-merge.html")!) }
            }
        }.padding(16).disabled(model.busy)
        .alert("Merge failed", isPresented: Binding(get: { model.error != nil }, set: { if !$0 { model.error = nil } })) { Button("OK") { model.error = nil } } message: { Text(model.error ?? "") }
        .sheet(isPresented: $model.browseReferences) { MergeReferenceChooser(model: model) }
    }
}

private struct MergeReferenceChooser: View {
    @ObservedObject var model: MergeWindowModel
    @State private var filter = ""
    @State private var selection: String?
    var body: some View {
        VStack(alignment: .leading, spacing: 12) {
            Text("Browse references").font(.headline)
            TextField("Filter", text: $filter)
            List(selection: $selection) { ForEach(model.branches.filter { filter.isEmpty || $0.label.localizedCaseInsensitiveContains(filter) }, id: \.name) { Text($0.label).tag($0.name) } }
            HStack { Spacer(); Button("Cancel") { model.browseReferences = false }.keyboardShortcut(.cancelAction)
                Button("OK") { if let selection { model.branchRevision = selection }; model.browseReferences = false }.disabled(selection == nil).keyboardShortcut(.defaultAction)
            }
        }.padding(16).frame(width: 580, height: 400)
    }
}
